export const APPCONSTANTS = {
    CATEGORIES: {
        CAREER_CATEGORIES: "CAREER_CATEGORIES",
        CAREERS: "CAREERS",
        CAREER_PER_UNIVERSITY: "CAREER_PER_UNIVERSITY",
        CAREER_DASHBOARDS: "CAREER_DASHBOARDS",
        CAREER_CLASIFFIED_POSTS: "CAREER_CLASSIFIED_POST",
        UNIVERSITIES: "UNIVERSITIES",
        CAREER_SECTIONS:{
            MATERIAL_ESTUDIO: 'MATERIAL',
            PAGINAS_OFICIALES: 'OFFICIAL_PAGES',
            PENSUM_ESTUDIOS: "PENSUM_ESTUDIOS",
            AREAS_TRABAJO: "AREAS_TRABAJO",
            EXPERIENCIAS_EGRESADOS: "EXPERIENCIAS",
            RECURSOS_UTILES: "RECURSOS_UTILES", 
            CONSEJOS: "CONSEJOS"
        }
    },
    HELPER_CARRER_REDIRECTIONS: {
        MATERIAL_ESTUDIO: "CAREER_MATERIAL_ESTUDIO",
        PAGINAS_OFICIALES: "CAREER_PAGINAS_OFICIALES",
        PENSUM_ESTUDIOS: "CAREER_PENSUM"
    },
    SCHEMAS : {
        POSTS_SCHEMA: 'posts',
        REACTIONS_SCHEMA: 'reactions',
        CATEGORIES_SCHEMA:'categories',
        FILES_SCHEMA: 'files'
    }
}