export const APPCONSTANTS = {
    CATEGORIES: {
        CAREER_CATEGORIES: "CAREER_CATEGORIES",
        CAREERS: "CAREERS",
        CAREER_DASHBOARDS: "CAREER_DASHBOARDS",
        CAREER_CLASIFFIED_POSTS: "CAREER_CLASSIFIED_POST",
        UNIVERSITIES: "UNIVERSITIES",
        PAGINAS_OFICIALES: "OFFICIAL_PAGES",
        PENSUM: "PENSUM",
        CAREER_REDIRECTIONS: {
            MATERIAL_ESTUDIO: "CAREER_MATERIAL_ESTUDIO",
            PAGINAS_OFICIALES: "CAREER_PAGINAS_OFICIALES",
            PENSUM: "CAREER_PENSUM"
        },
        CAREER_SECTIONS:{
            MATERIAL: 'MATERIAL',
            PAGINAS: 'PAGINAS',
            PENSUM: "PENSUM",
            TRABAJO: "TRABAJO",
            EXPERIENCIAS: "EXPERIENCIAS",
            RECURSOS: "RECURSOS", 
            CONSEJOS: "CONSEJOS"
        },
    },
    SCHEMAS : {
        POSTS_SCHEMA: 'posts',
        REACTIONS_SCHEMA: 'reactions',
        CATEGORIES_SCHEMA:'categories'
    }
}